name: Deploy to VPS

on:
  push:
    branches: [ "master" ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'conf/**'
      - 'docker/**'
      - 'docker-compose.yml'

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Connect to your VPS server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        password: ${{ secrets.VPS_PASSWORD }}

        script: |
          cd /projects/kuchp-release
          git pull
          docker-compose build
          docker-compose up -d
